[package]
name = "specialty_coffee_consumer_index"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11.18", features = ["json", "gzip", "brotli", "deflate", "rustls-tls"] }
tokio = { version = "1.28", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sqlx = { version = "0.6", features = ["runtime-tokio-rustls", "sqlite", "migrate", "offline"] }
anyhow = "1.0"

# [features]
# nightly = []
